#!/bin/bash


_get_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $REPO_MAN == "Man-Userbot" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL21yaXNtYW5heml6L01hbi1Vc2VyYm90L2FyY2hpdmUvTWFuLVVzZXJib3Quemlw" | base64 -d
    elif [[ $REPO_MAN == "Man-Userbot" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL21yaXNtYW5heml6L01hbi1Vc2VyYm90L2FyY2hpdmUvTWFuLVVzZXJib3Quemlw" | base64 -d
    elif [[ $REPO_MAN =~ $regex ]]
    then
        if [[ $REPO_MAN_BRANCH ]]
        then
            echo "${REPO_MAN}/archive/${REPO_MAN_BRANCH}.zip"
        else
            echo "${REPO_MAN}/archive/Man-Userbot.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL21yaXNtYW5heml6L01hbi1Vc2VyYm90L2FyY2hpdmUvTWFuLVVzZXJib3Quemlw" | base64 -d
    fi
}


_set_bot () {
    local zippath
    zippath="Man-Userbot.zip"
    echo "  ⚜ Downloading Man-UserBot Source Code ⚜"
    wget -q $(_get_repolink) -O "$zippath"
    echo "  ⚜ Unpacking Data ⚜"
    PATHMAN=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "  ⚜ Done ⚜"
    echo "  ⚜ Man-UserBot Cleaning ⚜"
    rm -rf "$zippath"
    sleep 5
    cd $PATHMAN
    echo "  ⚜ Starting Man-UserBot ⚜    "

    python3 ../setup/updater.py ../requirements.txt requirements.txt
    chmod -R 755 bin
    python3 -m userbot
}

_set_bot
